# Generated by Django 5.1.3 on 2025-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
