# Generated by Django 5.1.3 on 2025-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auction_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="auction_images/"),
        ),
    ]
