# Generated by Django 5.1.3 on 2025-02-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="image",
        ),
        migrations.AddField(
            model_name="auction",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
