# Generated by Django 5.1.3 on 2025-02-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_wishlist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wishlist",
            new_name="Watchlist",
        ),
    ]
