# Generated by Django 5.1.3 on 2025-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
