# Generated by Django 5.1.3 on 2025-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_auction_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
