# Generated by Django 5.1.3 on 2025-02-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_rename_bid_bids_amount_auction_bidder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("furniture", "Furniture"),
                    ("clothing", "Clothing"),
                    ("uncategorized", "Uncategorized"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
