# Generated by Django 5.1.3 on 2025-02-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_auction_category_wonauction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bids",
            options={"verbose_name_plural": "Bids"},
        ),
    ]
