# Generated by Django 5.1.3 on 2025-02-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="post_time",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=255),
        ),
    ]
