# Generated by Django 5.1.3 on 2025-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_auction_starting_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
