# Generated by Django 5.1.3 on 2025-03-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_alter_auction_starting_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="starting_price",
        ),
    ]
