# Generated by Django 5.1.3 on 2025-03-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_remove_auction_starting_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
