# Generated by Django 5.1.3 on 2025-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post_like_follow_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
