# Generated by Django 5.1.3 on 2025-03-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_post_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="like",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="network.post",
            ),
        ),
    ]
