# Generated by Django 5.1.3 on 2025-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_comment_id_alter_follow_id_alter_like_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count_likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
