# Generated by Django 5.1.3 on 2025-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_remove_follow_follow_follow_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="count_followers",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
