# Generated by Django 5.1.3 on 2024-11-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="roadmap",
        ),
    ]
